/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://rt7ykbewzngj7mnbadm56hmoki.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gvbapofwwjha5pvfocjnj437gy",
    "aws_cognito_identity_pool_id": "us-east-2:cbb18880-08d1-4c8d-9fda-2fb3a055ebd4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_BYcn5iks5",
    "aws_user_pools_web_client_id": "5fkb2tniq8b7beboffqvfeqokr",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "turbospork8240b5461b6f49b5b143568b97ece083195823-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
